### ISSUE TITLE
/^(?P<major>0|[1-9]\d*)\.(?P<minor>0|[1-9]\d*)\.(?P<patch>0|[1-9]\d*)(?:-(?P<prerelease>(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+(?P<buildmetadata>[0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$/gm

### ISSUE THREAD

**Issue by av1934413** [q0w/django-periodiq#40]

**Comment by q0w** [comment]
?

**Comment by priyanshu-panwar** [comment]
Hey @q0w , can I contribute to your project.
I am looking forward to contribute to some open source projects and this is a great one to start. If there's any issue or development feature please let me know.
Thank You

**Comment by q0w** [comment]
Hi, you can contribute to this project if you find bugs or possible features. For now I have not any features. But you can look at https://github.com/bogdanp/django_dramatiq as the main dependency of this project
